"""add ondelete restrict to domain_verifications user_id

Revision ID: b435ac6dcc92
Revises: 74091b034e8e
Create Date: 2026-08-29 22:56:17.970387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b435ac6dcc92'
down_revision: Union[str, Sequence[str], None] = '74091b034e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - ajustado a mano: el nombre de la constraint
    # se dejó explícito (en vez de None) para que downgrade() pueda referenciarla al revertir ###
    op.drop_constraint(op.f('domain_verifications_user_id_fkey'), 'domain_verifications', type_='foreignkey')
    op.create_foreign_key(
        'domain_verifications_user_id_fkey', 'domain_verifications', 'users', ['user_id'], ['id'],
        ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - ajustado a mano (ver nota en upgrade) ###
    op.drop_constraint(op.f('domain_verifications_user_id_fkey'), 'domain_verifications', type_='foreignkey')
    op.create_foreign_key(
        'domain_verifications_user_id_fkey', 'domain_verifications', 'users', ['user_id'], ['id'],
    )
    # ### end Alembic commands ###
